### PR TITLE
Java Solution

### PR DESCRIPTION
**Pull request by unon4all**
1. Added solution for Arrays question, i.e., Build Array from Permutation.
2. Check marked Arrays topic in Code list.

Hoping this time, things will go smooth.

### CODE REVIEW

**Comment by Bhuvnesh875** [comment]
This code doesn't match the relevant topic Arrays. Array topic means you should write a code which shows basic functions that are performed on an array. You can check the Array code in Cpp language. you can write this as a part of code for Arrays. Else everything is perfect ⭐

**Comment by unon4all** [comment]
Should i create a separate topic like Arrays Questions something like that or DSA-Arrays Assignment

**Comment by Bhuvnesh875** [comment]
make a file named ArraysJava.txt add some basic operations that are performed on an array like, delete, display, append, max n min element, sum ,average element along with this code as one of the class.

**Comment by unon4all** [comment]
Now I got the end goal ... next time I will send u the .txt file on Gmail before pulling a request ...

**Comment by Bhuvnesh875** [comment]
In this case you could have added new code to the same file and renamed it instead of starting from beginning, but it's ok, you'll learn gradually.

**Pull request closed without merging**
