### PR TITLE
main

### PR DESCRIPTION
**Pull request by unon4all**
1. Added  solution to the assignment 1st in Arrays topic.
2. The language used is JAVA.

I have the following questions …
1.  The question of which I solved is from topic ARRAYS, but see there are many problems in the same topic, so how will I name those .txt files as you mentioned TOPIC NAME  must be same everywhere.

I'm just a beginner to these things, so sorry if I have done things wrong … please let me know that … it would be so helpful …

I will continue to contribute to this project … For demo, I'm just adding one file … If everything went smoothly, I will continue to upload more solutions.

### CODE REVIEW

**Review by Saurabhsharma884 — APPROVED** [review]

**Comment by Bhuvnesh875** [comment]
please wait for sometime. I'll let you know very soon

**Comment by Bhuvnesh875** [comment]
Hello @unon4all ,
First of all no need to say sorry as everyone is here to learn.

There are some points, pls do work on the following and open a pull request again:
- Open different Pull requests for different codes as 3-4 files are modified it becomes a bit messy to review the changes and you will also miss out something.
- As you said the topic name cant be same everywhere, so i have made the necessary changes in the contributing.md. The topic name should be same in ```files section of links.js``` and ```txt file in Codes folder```. And it should be same in ```args[1] of links.js``` and ```Topic.js```. Refer to previous codes' names for naming the files as it makes the code 'easy-to-understand'.
- Array means all the common operations performed on an array should be included else if there is any operation that is not commonly performed on an array add them in algorithm section.

**Comment by unon4all** [comment]
@Bhuvnesh875  kind request can u verify the changes till now, I will do a separate pull request for it …. N after that I will do different pull request for different codes … or should I start from scratch. As you say ?

**Comment by Bhuvnesh875** [comment]
My advice would be start from scratch ..and keep the topic name easily understandable.

**Comment by unon4all** [comment]
OK. Ping u soon.

**Pull request closed without merging**
